site_name: Bennert
docs_dir: docs
site_dir: _site

theme:
  name: material
  features:
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
    - navigation.indexes
    # - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.integrate

  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
        # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom

plugins:
  - search
  - mermaid2
  - open-in-new-tab
  - i18n:
      languages:
        nl: '<img style="height: 10px; border: 0px;" alt="nl" class="twemoji" src="https://twemoji.maxcdn.com/v/latest/svg/1f1f3-1f1f1.svg" title="nederlands" /> Nederlands'
        en: '<img style="height: 10px; border: 0px;" alt="en" class="twemoji" src="https://twemoji.maxcdn.com/v/latest/svg/1f1ec-1f1e7.svg" title="english" /> English'
      default_language: nl

extra_javascript:
    - https://unpkg.com/mermaid/dist/mermaid.min.js

nav:
- Thuis: index.md
- Home: index.en.md
- Introductie: Intro/index.md
- Intro: Intro/index.en.md
- Persoonlijkheid: Personality/index.md
- Personality: Personality/index.en.md
- Groei/Growth:
  - Overzicht: PersonalGrowth/index.md
  - Overview: PersonalGrowth/index.en.md
  - Ontdek 6 menselijke behoeften: PersonalGrowth/Discover6HumanNeeds/index.md
  - Discover 6 human needs: PersonalGrowth/Discover6HumanNeeds/index.en.md
  - Pad naar Groei: PersonalGrowth/PathToGrowth/index.md
  - Path to Growth: PersonalGrowth/PathToGrowth/index.en.md
  - Pyramide van Meesterschap: PersonalGrowth/PyramidOfMastery/index.md
  - Pyramid of Mastery: PersonalGrowth/PyramidOfMastery/index.en.md
  - Versterk je conditie: PersonalGrowth/EmpoweringState/index.md
  - Empowering State: PersonalGrowth/EmpoweringState/index.en.md
  - Groeien: PersonalGrowth/Thrive/index.md
  - Thrive: PersonalGrowth/Thrive/index.en.md

extra:
  alternate:
    - name: Nederlands
      link: /nl/
      lang: nl
    - name: English
      link: /en/
      lang: en
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/bennertdewijs
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/bennert-de-wijs-5938aa2/

copyright: |
  &copy; 2023 <a href="https://www.bennert.nl/" target="_blank" rel="noopener">Bennert</a>