site_name: Bennert

theme:
  name: material
  features:
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.integrate
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/bennertdewijs
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/bennert-de-wijs-5938aa2/

copyright: |
  &copy; 2023 <a href="https://www.bennert.nl/" target="_blank" rel="noopener">Bennert</a>