site_name: Bennert
docs_dir: docs
site_dir: _site

theme:
  name: material
  features:
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
    - navigation.indexes
    # - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.integrate

  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - open-in-new-tab
  - i18n:
      languages:
        nl: '<img style="height: 10px; border: 0px;" alt="nl" class="twemoji" src="https://twemoji.maxcdn.com/v/latest/svg/1f1f3-1f1f1.svg" title="nederlands" /> Nederlands'
        en: '<img style="height: 10px; border: 0px;" alt="en" class="twemoji" src="https://twemoji.maxcdn.com/v/latest/svg/1f1ec-1f1e7.svg" title="english" /> English'
      default_language: nl

nav:
- Thuis: index.md
- Home: index.en.md
- Intro: Intro
- Talents: Talents

extra:
  alternate:
    - name: Nederlands
      link: /nl/
      lang: nl
    - name: English
      link: /en/
      lang: en
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/bennertdewijs
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/bennert-de-wijs-5938aa2/

copyright: |
  &copy; 2023 <a href="https://www.bennert.nl/" target="_blank" rel="noopener">Bennert</a>